version: 0.2
phases:
  pre_build:
    commands:
      - echo Entering Pre-Build .....
      - $(aws ecr get-login)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo TAG:$TAG
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
      - echo IMAGE_URI:$IMAGE_URI
  build:
    commands:
      - echo building tag $IMAGE_URI
      - docker build --tag "$IMAGE_URI" .

    post_build:
      commands:
        - docker push "$IMAGE_URI"
        - printf '[{"name":"simple-app","imageUri":"%s"}]' "$IMAGE_URI" > images.json
        - ls -lah
artifacts:
  files:
    - '*/images.json'
  discard-paths: yes